name: 'Upload Release Assets'
description: 'Upload release assets to an existing release in your repository, including glob support'
author: 'wireapp'
inputs:
  asset_paths:
    description: 'The paths to the assets you want to upload as a JSON array. You can use a glob pattern.'
    required: true
  upload_url:
    description: 'Set the asset upload URL'
    required: true
outputs:
  browser_download_urls:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
